# Generated by Django 4.2.7 on 2025-05-28 11:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clinica', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/')),
                ('citas_por_dia', models.IntegerField(default=3)),
                ('dias_max_agenda', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('codigo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('EMAIL', 'Correo Electrónico'), ('SMS', 'Mensaje de Texto'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('contenido', models.TextField(help_text='Usa {variables} para contenido dinámico')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='diagnostico',
            new_name='info_diagnostico',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='receta',
            new_name='info_receta',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='cita',
            name='canal_cita',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('TELEFONICA', 'Telefónica')], default='PRESENCIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='link_virtual',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='prioridad',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('EMERGENCIA', 'Emergencia')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='tiempo_espera',
            field=models.IntegerField(blank=True, help_text='Tiempo de espera en minutos', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(choices=[('PRIMERA_VEZ', 'Primera Vez'), ('SEGUIMIENTO', 'Seguimiento'), ('CONTROL', 'Control'), ('EMERGENCIA', 'Emergencia')], default='PRIMERA_VEZ', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultorio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad_principal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctores_principal', to='app_citas.especialidad'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidades_adicionales',
            field=models.ManyToManyField(blank=True, related_name='doctores_adicionales', to='app_citas.especialidad'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viudo')], max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('puede_donar_a', models.ManyToManyField(blank=True, to='app_citas.tiposangre')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_arterial', models.CharField(max_length=20)),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_citas.cita')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('modelo_afectado', models.CharField(max_length=50)),
                ('id_registro', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicaciones_generales', models.TextField()),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta_medica', to='app_citas.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_citas.notificaciontemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=50)),
                ('indicaciones', models.TextField()),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_citas.receta')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_sanguineo', models.CharField(max_length=3)),
                ('alergias', models.TextField(blank=True)),
                ('enfermedades_cronicas', models.TextField(blank=True)),
                ('cirugias_previas', models.TextField(blank=True)),
                ('medicamentos_actuales', models.TextField(blank=True)),
                ('antecedentes_familiares', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_citas.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('recomendaciones', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico_completo', to='app_citas.cita')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_citas.cita')),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_citas.genero'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_citas.tiposangre'),
        ),
        migrations.CreateModel(
            name='HorarioDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_citas.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'dia_semana')},
            },
        ),
    ]
