# Generated by Django 4.2.7 on 2025-06-10 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_citas', '0003_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='duracion_cita',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='especialidad_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctores_principal', to='app_citas.especialidad'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='horario_fin',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='horario_inicio',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='numero_colegiado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Colegiado'),
        ),
    ]
